server:
  port: 8081

logging:
  level:
    root: INFO
    com.ezappx: DEBUG

spring:
  banner:
    charset: UTF-8
    location: banner.txt
  data:
    mongodb:
      host: 10.109.252.210
      port: 27017
      database: ezappx

ezappx:
  builder:
    userProjectDirName: UserProjects