server:
  port: 8080
  use-forward-headers: true

spring:
  banner:
    charset: UTF-8
    location: banner.txt
  data:
    mongodb:
      host: 10.109.252.210
      port: 27017
      database: ezappx

logging:
  level:
    root: INFO
    com.ezappx: DEBUG

ezappx:
  builder:
    builderApi: http://build.ezappx.com/api/v1
    androidBuilderApi: http://build.ezappx.com/api/v1/android/build
    iosBuilderApi: http://build.ezappx.com/api/v1/iosBuilderApi/build
  file:
    uploadApi: http://www.ezappx.com/upload/binaryData
    resourceApi: http://www.ezappx.com/resource/static
  storage:
    storeApi: http://www.ezappx.com/storage/store
    loadApi: http://www.ezappx.com/storage/load

