server:
  port: 8080
  use-forward-headers: true

spring:
  banner:
    charset: UTF-8
    location: banner.txt
  data:
    mongodb:
      host: 10.109.252.77
      port: 27017
      database: ezappx

logging:
  level:
    root: INFO
    com.ezappx: DEBUG

ezappx:
  builder:
    builderApi: http://localhost:8081/api/v1
    androidBuilderApi: http://localhost:8081/api/v1/android/build
    iosBuilderApi: http://localhost:8081/api/v1/iosBuilderApi/build
  file:
    uploadApi: http://localhost:8080/upload/binaryData
    resourceApi: http://localhost:8080/resource/static
  storage:
    storeApi: http://localhost:8080/storage/store
    loadApi: http://localhost:8080/storage/load

